apiVersion: apps/v1
kind: Deployment
metadata:
  name: duncans-example-deployment
spec:
  replicas: 2
  template:
    spec:
      containers:
        - image: duncans-example-app:.0
          name: duncans-example-app
          env:
            - name: APP_VERSION
              value: F@#$ DA POLICE!!
