kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namePrefix: prod-

resources:
  - ../../base

patches:
  - target:
      name: duncans-example-deployment
      kind: Deployment
    path: version.yaml
  - target:
      name: duncans-example-deployment
      kind: Deployment
    path: redundant-servers.yaml
