apiVersion: apps/v1
kind: Deployment
metadata:
  name: duncans-example-deployment
spec:
  replicas: 2
  template:
    spec:
      containers:
        - image: duncans-example-app:1.0
          name: duncans-example-app
