apiVersion: apps/v1
kind: Deployment
metadata:
  name: duncans-example-deployment
spec:
  selector:
    matchLabels:
      app: duncans-example-app
  template:
    metadata:
      labels:
        app: duncans-example-app
    spec:
      containers:
        - name: duncans-example-app
          ports:
            - containerPort: 80
