apiVersion: apps/v1
kind: Deployment
metadata:
  name: duncans-example-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: duncans-example-app
  template:
    metadata:
      labels:
        app: duncans-example-app
    spec:
      containers:
        - image: duncans-example-app:2.0
          name: duncans-example-app
          ports:
            - containerPort: 80
